DROP PROCEDURE IF EXISTS `imap_contacts`.`CheckCredentials`;

DELIMITER |

CREATE DEFINER = `imap_contacts` PROCEDURE `imap_contacts`.`CheckCredentials` (IN u_email BINARY(120), IN u_password BINARY(32))
LANGUAGE SQL
NOT DETERMINISTIC
READS SQL DATA
SQL SECURITY DEFINER
COMMENT 'Test les informations d\'identification'
BEGIN
	DECLARE STORED_PASSWORD			BINARY(32) DEFAULT NULL;
	DECLARE CURR_SELECT_PASSWORD	CURSOR FOR SELECT `password` FROM `users` WHERE `email` = u_email;

	IF RPAD(0x00, 120, 0x00) <=> u_email THEN
		SIGNAL SQLSTATE VALUE '45000' SET MYSQL_ERRNO = 10002, MESSAGE_TEXT = 'User email cannot be empty';
	ELSEIF RPAD(0x00, 32, 0x00) <=> u_password THEN
		SIGNAL SQLSTATE VALUE '45000' SET MYSQL_ERRNO = 10003, MESSAGE_TEXT = 'User password cannot be empty';
	ELSE
		OPEN	CURR_SELECT_PASSWORD;
		FETCH	CURR_SELECT_PASSWORD INTO STORED_PASSWORD;
		CLOSE	CURR_SELECT_PASSWORD;

		IF STORED_PASSWORD IS NOT NULL THEN
			IF STORED_PASSWORD <=> u_password THEN
				SELECT TRUE;
			END IF;
		END IF;
	END IF;
END;
|

DELIMITER ;
